version: '3.9'

services:
  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - nextcloud-net

  cloud:
    image: nextcloud:fpm
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
    volumes:
      - ./app:/var/www/html
    networks:
      - nextcloud-net

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - cloud
      - certbot-init
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/var/www/html:ro
      - ./certs:/etc/letsencrypt
      - ./config:/etc/letsencrypt/config
      - ./nginx/certbot:/var/www/certbot
    networks:
      - nextcloud-net

  certbot-init:
    image: certbot/certbot
    container_name: certbot-init
    command: >
      sh -c "mkdir -p /var/www/certbot &&
             certbot certonly --webroot
             --webroot-path=/var/www/certbot
             -d ${DOMAIN}
             -m ${EMAIL}
             --agree-tos --no-eff-email --force-renewal || true"
    volumes:
      - ./certs:/etc/letsencrypt
      - ./config:/etc/letsencrypt/config
      - ./nginx/certbot:/var/www/certbot
    networks:
      - nextcloud-net
    environment:
      - TZ=${TZ}
    restart: "no"

  certbot-renew:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certs:/etc/letsencrypt
      - ./config:/etc/letsencrypt/config
      - ./nginx/certbot:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --quiet; sleep 12h; done"
    networks:
      - nextcloud-net

networks:
  nextcloud-net:
